<?php
/**
 * Created by PhpStorm.
 * User: andres
 * Date: 2018-12-20
 * Time: 00:09
 */

namespace Subsistema\Providers;


use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'Subsistema\Http\Controllers';

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::prefix('subsistemas')
            ->middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('app/Modules/Subsistema/Routes/web.php'));
    }

    protected function mapApiRoutes()
    {
        Route::prefix('api/subsistemas')
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('app/Modules/Subsistema/Routes/api.php'));
    }
}
