SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.ceneval_preguntas;
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (1, 'DIFICULTAD PARA CAMINAR', 'IMP_CAM', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (2, 'DIFICULTAD  PARA ESCUCHAR, AUN A CORTA DISTANCIA', 'IMP_ECU', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (3, 'PROBLEMAS GRAVES PARA VER, AUN CON LENTES', 'IMP_VER', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (4, 'PROBLEMAS DE CONDUCTA', 'IMP_CON', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (5, 'PROBLEMAS DE ANSIEDAD/ESTRÉS', 'IMP_PAN', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (6, 'PROBLEMAS DE AGRESIVIDAD', 'IMP_PCA', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (7, 'PROBLEMAS DE DEPRESIÓN', 'IMP_PDP', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (8, 'PROBLEMAS DE ATENCIÓN', 'IMP_PAT', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (9, 'OBESIDAD', 'IMP_POB', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (10, 'ANOREXIA O BULIMIA', 'IMP_PAB', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (11, 'MADRE', 'LI_MAD', 4, 119);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (12, 'PADRE', 'LI_PAD', 4, 119);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (13, '¿CUÁL ES EL RÉGIMEN DE SOSTENIMIENTO DE LA ESCUELA EN LA QUE ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'REG_PROC', 5, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (14, '¿EN QUÉ TIPO DE ESCUELA ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'TIP_SEC', 6, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (15, '¿EN QUÉ TURNO ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'TURNO', 7, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (16, '¿CUÁL FUE TU PROMEDIO FINAL EN SEGUNDO AÑO DE LA SECUNDARIA?', 'PROM_SEC', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (17, '¿CUÁL FUE TU PROMEDIO FINAL DE MATEMÁTICAS EN SEGUNDO AÑO DE LA SECUNDARIA?', 'PROM_MAT', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (18, '¿CUÁL FUE TU PROMEDIO FINAL DE ESPAÑOL EN SEGUNDO AÑO DE SECUNDARIA?', 'PROM_ESP', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (19, '¿RECIBISTE BECA POR NECESIDAD ECONÓMICA EN LA SECUNDARIA?', 'BEC_NEC', 3, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (22, 'FALTO A CLASES', 'FRE_FCL', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (23, 'LLEVO TODOS LOS MATERIALES QUE UTILIZO EN LAS CLASES (LIBROS, CUADERNOS, LÁPICES, ETC.)', 'FRE_LLTM', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (24, 'PARTICIPO DURANTE LA CLASE', 'FRE_PDC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (25, 'DEDICO TIEMPO A ESTUDIAR FUERA DE LA ESCUELA', 'FRE_DTE', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (26, 'ENTREGO A TIEMPO LAS TAREAS QUE ME DEJAN EN LA ESCUELA', 'FRE_ETTE', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (27, 'PARTICIPO EN LA PLANEACIÓN DE LAS ACTIVIDADES', 'FRE_PPA', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (28, 'COLABORO EN EL DESARROLLO DE ESTRATEGIAS PARA CUMPLIR CON LAS METAS DEL TRABAJO', 'FRE_CDE', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (29, 'INTERVENGO PARA TRATAR DE SOLUCIONAR CONFLICTOS ENTRE LOS MIEMBROS DEL EQUIPO', 'FRE_TSC', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (30, 'REALIZO SUGERENCIAS PARA MEJORAR EL DESEMPEÑO DEL EQUIPO', 'FRE_SME', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (31, 'CUMPLO CON LAS TAREAS QUE ME TOCA REALIZAR', 'FRE_CTR', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (36, 'SI ME ESFUERZO LO SUFICIENTE, TENDRÉ ÉXITO EN LA ESCUELA', 'IDE_ESE', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (37, 'EL QUE ME VAYA BIEN O MAL EN LA ESCUELA DEPENDE TOTALMENTE DE MÍ', 'IDE_VBM', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (38, 'SI TUVIERA OTROS MAESTROS ME IRÍA MEJOR EN LA ESCUELA', 'IDE_OME', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (39, 'SI ME LO PROPONGO, ME VA MEJOR EN LA ESCUELA', 'IDE_PPM', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (40, 'SI MI FAMILIA ME APOYARA MÁS, ME IRÍA MEJOR EN LA ESCUELA', 'IDE_FAM', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (41, 'MIS CALIFICACIONES EN LA ESCUELA SE DEBEN A LA SUERTE QUE TENGO', 'IDE_CES', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (42, 'MIS CALIFICACIONES EN LA ESCUELA SE DEBEN A COSAS QUE NO PUEDO CAMBIAR', 'IDE_CEC', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (43, 'LOS PROBLEMAS INESPERADOS ME DESANIMAN', 'DES_DESA', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (44, 'SOY UNA PERSONA QUE SE ESMERA', 'DES_ESME', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (45, 'TERMINO TODO LO QUE EMPIEZO', 'DES_TERM', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (46, 'SOY UNA PERSONA QUE TRABAJA DURO', 'DES_DURO', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (47, 'PRESENTAR UN TRABAJO FRENTE A UN GRUPO', 'SOC_PTFG', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (48, 'INICIAR Y MANTENER UNA CONVERSACIÓN CON COMPAÑEROS QUE NO CONOCES', 'SOC_IMC', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (49, 'PARTICIPAR DURANTE LAS CLASES', 'SOC_PDC', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (50, 'PLANTEAR DUDAS A LOS MAESTROS', 'SOC_PDM', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (60, 'PLANEAR TUS ACTIVIDADES ESCOLARES', 'HAB_PTAE', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (61, 'IDENTIFICAR LAS DIFICULTADES PARA ALCANZAR TUS METAS', 'HAB_DAM', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (62, 'APRECIAR EL ARTE (COMO LA MÚSICA, LA DANZA Y LA PINTURA)', 'HAB_AEA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (63, 'TENER UN ESTILO DE VIDA SALUDABLE (HACER EJERCICIO, COMER SANAMENTE)', 'HAB_TEVS', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (64, 'LEER TEXTOS EN INGLÉS', 'HAB_LTI', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (65, 'EXPRESAR TUS IDEAS EN UN ESCRITO', 'HAB_ETI', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (66, 'EXPRESAR TUS IDEAS VERBALMENTE (DE MANERA ORAL)', 'HAB_ETIV', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (67, 'MANEJAR HOJAS DE CÁLCULO (COMO EXCEL)', 'HAB_MHC', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (68, 'ORDENAR INFORMACIÓN', 'HAB_OIF', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (69, 'IDENTIFICAR EL OBJETIVO DE LAS ACTIVIDADES QUE TE DEJAN EN LA ESCUELA', 'HAB_IOA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (70, 'EVALUAR TUS OPINIONES Y LAS DE OTRAS PERSONAS', 'HAB_ETO', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (71, 'APRENDER POR TI MISMO(A)', 'HAB_APM', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (72, 'REALIZAR EXPERIMENTOS EN LABORATORIOS O EN AMBIENTES NATURALES', 'HAB_REL', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (73, 'IDENTIFICAR Y SOLICITAR LA APLICACIÓN DE LAS LEYES QUE TE PROTEGEN COMO CIUDADANO(A)', 'HAB_SAL', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (74, 'DIALOGAR Y APRENDER DE OTRAS PERSONAS DISTINTOS PUNTOS DE VISTA Y TRADICIONES CULTURALES', 'HAB_DAP', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (75, 'CUIDAR EL MEDIO AMBIENTE', 'HAB_CMA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (76, '¿CUÁL ES EL NIVEL MÁXIMO DE ESTUDIOS QUE TE GUSTARÍA ALCANZAR?', 'EST_ALCA', 14, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (88, 'GOLPEARAN O MALTRATARAN FÍSICAMENTE?', 'DAN_MALF', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (89, 'OFENDIERAN CON INSULTOS, GROSERÍAS O APODOS HIRIENTES?', 'DAN_OFI', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (90, 'EXCLUYERAN, IGNORARAN O RECHAZARAN?', 'DAN_EIR', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (91, 'ROBARAN, ESCONDIERAN O QUITARAN TUS COSAS?', 'DAN_REQC', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (92, 'MOLESTARAN POR MEDIO DE REDES SOCIALES (FACEBOOK, TWITTER, ETC.), CORREO ELECTRÓNICO O MENSAJES DE TEXTO POR EL CELULAR?', 'DAN_MFT', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (93, 'FORZARAN A HACER COSAS QUE TÚ NO QUERÍAS?', 'DAN_FHC', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (94, '¿CUÁL ES EL MÁXIMO NIVEL DE ESTUDIOS DE TU MADRE (AUNQUE HAYA FALLECIDO)?', 'ESCO_MAD', 16, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (95, '¿CUÁL ES EL MÁXIMO NIVEL DE ESTUDIOS DE TU PADRE (AUNQUE HAYA FALLECIDO)?', 'ESCO_PAD', 16, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (96, '¿CUÁNTOS LIBROS HAY EN TU CASA? (NO CONSIDERES REVISTAS, PERIÓDICOS O TUS LIBROS DE TEXTO)', 'CUAN_LIB', 17, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (97, 'LÍNEA TELEFÓNICA FIJA', 'SER_TELE', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (98, 'LAVADORA DE ROPA', 'SER_LAV', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (99, 'REFRIGERADOR', 'SER_REF', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (100, 'HORNO DE MICROONDAS', 'SER_HOR', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (101, 'INTERNET', 'SER_INTE', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (102, 'TELEVISIÓN DE PAGA (IZZI, SKY, ETC.)', 'SER_CABL', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (103, 'TABLETA (IPAD, SAMSUNG GALAXY, PLAYBOOK, ETC.)', 'SER_TABL', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (104, 'COMPUTADORA', 'BIEN_PC', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (105, 'TELEVISOR', 'SER_TV', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (106, 'AUTOMÓVIL', 'SER_AUTO', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (107, 'BAÑOS COMPLETOS (CON REGADERA)', 'SER_BANO', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (108, '¿CUÁNTAS VECES HAS SALIDO DE VACACIONES DENTRO DE LA REPÚBLICA MEXICANA EN LOS ÚLTIMOS 2 AÑOS?', 'VAC_RM', 9, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (109, 'PADRES', 'INF_PAD', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (110, 'HERMANOS', 'INF_HER', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (111, 'AMIGOS', 'INF_AMI', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (112, 'PROFESORES', 'INF_PRF', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (113, 'PSICÓLOGOS U ORIENTADORES EDUCATIVOS', 'INF_POE', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (114, '¿UTILIZASTE LA GUÍA INTERACTIVA PARA PREPARARTE PARA EL EXANI-I (EXAMEN NACIONAL DE INGRESO A LA EDUCACIÓN MEDIA SUPERIOR)?', 'UTI_GUI', 3, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (115, 'EN TU ESCUELA', 'CUR_ESC', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (116, 'EN UNA INSTITUCIÓN PARTICULAR', 'CUR_IPA', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (117, 'CON UN MAESTRO PARTICULAR', 'CUR_MPA', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (118, '¿ENFRENTAS ALGUNAS DE LAS SIGUIENTES CONDICIONES?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (119, '¿ALGUNO DE TUS PADRES HABLA UNA LENGUA INDÍGENA O UN DIALECTO?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (120, '¿CON QUÉ FRECUENCIA REALIZAS LO SIGUIENTE?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (121, '¿CON QUÉ FRECUENCIA REALIZAS LO SIGUIENTE CUANDO TRABAJAS EN EQUIPO?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (123, 'INDICA QUÉ TANTO TE IDENTIFICAS CON LAS SIGUIENTES AFIRMACIONES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (124, 'INDICA QUÉ TANTO TE DESCRIBEN LAS SIGUIENTES AFIRMACIONES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (125, 'CALIFICA TU NIVEL DE HABILIDAD SOCIAL PARA REALIZAR LAS SIGUIENTES ACTIVIDADES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (128, 'CALIFICA TU NIVEL DE HABILIDAD PARA REALIZAR LAS SIGUIENTES ACTIVIDADES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (131, '¿QUÉ TANTO DAÑO TE CAUSÓ QUE TUS COMPAÑEROS EN LA SECUNDARIA TE…', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (132, '¿CUENTAS CON LOS SIGUIENTES BIENES Y SERVICIOS EN TU CASA?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (133, '¿CUÁNTOS DE LOS SIGUIENTES BIENES TIENES EN TU CASA?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (134, '¿QUÉ TANTO INFLUYERON LAS SIGUIENTES PERSONAS PARA ELEGIR LA ESCUELA PARA ESTUDIAR EL NIVEL MEDIO SUPERIOR?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (135, '¿TOMASTE UN CURSO DE PREPARACIÓN PARA EL EXANI-I (EXAMEN NACIONAL DE INGRESO A LA EDUCACIÓN MEDIA SUPERIOR)?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (142, 'LLEGO A TIEMPO A CLASES', 'FRE_LTC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (143, 'HAGO LOS EJERCICIOS QUE ME SOLICITAN EN LAS CLASES', 'FRE_HESC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (145, 'PONGO ATENCIÓN DURANTE LAS CLASES', 'FRE_PADC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (146, 'PARTICIPO EN ACTIVIDADES EXTRACURRICULARES QUE SE REALIZAN EN LA ESCUELA (ACTIVIDADES DEPORTIVAS, ARTÍSTICAS, ETC.)', 'FRE_PAEC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (147, 'SOY UNA PERSONA QUE SE ESFUERZA', 'DES_ESFU', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (148, 'PUEDO SUPERAR LOS OBSTÁCULOS QUE SE INTERPONEN PARA ALCANZAR MIS OBJETIVOS', 'DES_SOIO', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (149, 'HE ALCANZADO METAS QUE REQUIRIERON AÑOS DE ESFUERZO', 'DES_META', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (157, 'INDICA TU GRADO DE ACUERDO CON LOS SIGUIENTES ENUNCIADOS', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (158, 'PUEDO CAPTAR CON FACILIDAD SI OTRA PERSONA QUIERE PARTICIPAR EN UNA CONVERSACIÓN', 'GRA_PART', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (159, 'PUEDO IDENTIFICAR FÁCILMENTE SI UNA PERSONA DICE UNA COSA, CUANDO EN REALIDAD QUIERE DECIR OTRA', 'GRA_COSA', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (160, 'TENGO FACILIDAD PARA PREDECIR CÓMO SE SENTIRÁ OTRA PERSONA', 'GRA_PRSE', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (161, 'ME DOY CUENTA CUANDO ESTOY SIENDO ENTROMETIDO, INCLUSO SI LA OTRA PERSONA NO ME LO DICE', 'GRA_ENTR', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (162, 'PUEDO DARME CUENTA SI OTRA PERSONA ESTÁ OCULTANDO SUS VERDADERAS EMOCIONES', 'GRA_OCUL', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (163, 'ME ESFUERZO PARA QUE LOS DEMÁS ME ENTIENDAN', 'GRA_ESFU', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (164, 'ME RESULTA FÁCIL PONERME EN EL LUGAR DE OTRA PERSONA', 'GRA_LUGA', 20, 157);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (173, '¿HASTA QUE NIVEL EDUCATIVO QUIEREN TUS PADRES QUE ESTUDIES?', 'NIV_EDU', 21, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (174, '¿CUÁNTAS PERSONAS VIVEN EN TU CASA?', 'CPV_CASA', 22, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (175, 'GENERALES', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (177, 'INDICA QUÉ TANTO ESTAS DE ACUERDO CON LOS SIGUIENTES ENUNCIADOS', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (178, 'SOY UNA PERSONA DIGNA DE APRECIO, AL MENOS EN IGUAL MEDIDA QUE LOS DEMÁS', 'ACU_PDA', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (179, 'A VECES PIENSO QUE NO SOY BUENO(A) PARA NADA', 'ACU_BPN', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (180, 'CREO QUE TENGO UN BUEN NÚMERO DE CUALIDADES', 'ACU_BNC', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (181, 'EN GENERAL, ME INCLINO A PENSAR QUE SOY UN(A) FRACASADO(A)', 'ACU_IPF', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (182, 'SOY CAPAZ DE HACER LAS COSAS TAN BIEN COMO LA MAYORÍA DE LA GENTE', 'ACU_CMG', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (183, 'SIENTO QUE NO TENGO MUCHOS MOTIVOS PARA SENTIRME ORGULLOSO(A) DE MI', 'ACU_NMO', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (184, 'TENGO UNA ACTITUD POSITIVA HACIA MÍ MISMO(A)', 'ACU_TAP', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (185, 'EN GENERAL, ESTOY SATISFECHO(A) CONMIGO MISMO(A)', 'ACU_ESC', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (186, 'DESEARÍA VALORARME MÁS A MÍ MISMO(A)', 'ACU_DVM', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (187, 'A VECES ME SIENTO VERDADERAMENTE INÚTIL', 'ACU_SVI', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (188, '¿CON QUE FRECUENCIA REALIZAS LO SIGUIENTE CUANDO ESTUDIAS?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (189, 'PONGO MÁS ATENCIÓN CUANDO ENCUENTRO INFORMACIÓN IMPORTANTE', 'FEST_PAC', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (190, 'INVENTO MIS PROPIOS EJEMPLOS PARA ENTENDER MEJOR LA INFORMACIÓN', 'FEST_IPE', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (191, 'HAGO DIBUJOS O DIAGRAMAS', 'FEST_HDD', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (192, 'PONGO EN MIS PROPIAS PALABRAS LA INFORMACIÓN  NUEVA', 'FEST_PPI', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (193, 'IDENTIFICO LA ESTRUCTURA Y ORGANIZACIÓN DE LA INFORMACIÓN', 'FEST_EOI', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (194, 'RELACIONO LA INFORMACIÓN NUEVA CON LO QUE YA CONOZCO', 'FEST_RIC', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (195, 'ESTUDIO TODA LA INFORMACIÓN EN UN ÚNICO MOMENTO', 'FEST_IUM', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (196, 'ESTUDIO POR PARTES LA INFORMACIÓN DISPONIBLE', 'FEST_EID', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (197, 'PONGO MAYOR ATENCIÓN EN LAS IDEAS GENERALES', 'FEST_AIG', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (198, 'PONGO MAYOR ATENCIÓN EN LAS IDEAS ESPECÍFICAS', 'FEST_AIE', 10, 188);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (199, 'CALIFICA TU NIVEL DE HABILIDAD PARA…', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (200, 'OFRECER UNA DISCULPA', 'NIVH_ODI', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (201, 'ADMITIR QUE TENGO DIFICULTADES', 'NIVH_ATD', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (202, 'PEDIR AYUDA', 'NIVH_PAY', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (203, 'ADMITIR QUE TENGO MIEDO', 'NIVH_ATM', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (204, 'ACEPTAR QUE NO SÉ SOBRE ALGÚN TEMA', 'NIVH_ANT', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (205, 'PEDIR UNA CRÍTICA CONSTRUCTIVA', 'NIVH_PCC', 13, 199);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (206, 'SIN CONTAR EL BAÑO, LA COCINA Y LOS PASILLOS, ¿CUÁNTOS CUARTOS TIENE TU CASA?', 'CUARTOS', 22, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (207, '¿QUÉ TANTO CONSIDERASTE LOS SIGUIENTES MEDIOS AL ELEGIR LA ESCUELA PARA ESTUDIAR EL NIVEL MEDIO SUPERIOR?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (208, 'FOLLETOS', 'CAR_FOLL', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (209, 'GUÍAS DE CARRERAS', 'CAR_GUIA', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (210, 'PÁGINAS DE INTERNET SOBRE ORIENTACIÓN VOCACIONAL', 'CAR_PIOV', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (211, 'PRUEBAS O TEST DE ORIENTACIÓN VOCACIONAL', 'CAR_PTOV', 18, 207);
SET FOREIGN_KEY_CHECKS = 1;
