SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.ceneval_preguntas;
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (1, 'DIFICULTAD PARA CAMINAR', 'IMP_CAM', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (2, 'DIFICULTAD  PARA ESCUCHAR, AUN A CORTA DISTANCIA', 'IMP_ECU', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (3, 'PROBLEMAS GRAVES PARA VER, AUN CON LENTES', 'IMP_VER', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (4, 'PROBLEMAS DE CONDUCTA', 'IMP_CON', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (5, 'PROBLEMAS DE ANSIEDAD/ESTRÉS', 'IMP_PAN', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (6, 'PROBLEMAS DE AGRESIVIDAD', 'IMP_PCA', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (7, 'PROBLEMAS DE DEPRESIÓN', 'IMP_PDP', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (8, 'PROBLEMAS DE ATENCIÓN', 'IMP_PAT', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (9, 'OBESIDAD', 'IMP_POB', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (10, 'ANOREXIA O BULIMIA', 'IMP_PAB', 3, 118);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (11, 'MADRE', 'LI_MAD', 4, 119);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (12, 'PADRE', 'LI_PAD', 4, 119);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (13, '¿CUÁL ES EL RÉGIMEN DE SOSTENIMIENTO DE LA ESCUELA EN LA QUE ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'REG_PROC', 5, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (14, '¿EN QUÉ TIPO DE ESCUELA ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'TIP_SEC', 6, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (15, '¿EN QUÉ TURNO ESTUDIASTE EL ÚLTIMO AÑO DE SECUNDARIA?', 'TURNO', 7, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (16, '¿CUÁL FUE TU PROMEDIO FINAL EN SEGUNDO AÑO DE LA SECUNDARIA?', 'PROM_SEC', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (17, '¿CUÁL FUE TU PROMEDIO FINAL DE MATEMÁTICAS EN SEGUNDO AÑO DE LA SECUNDARIA?', 'PROM_MAT', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (18, '¿CUÁL FUE TU PROMEDIO FINAL DE ESPAÑOL EN SEGUNDO AÑO DE SECUNDARIA?', 'PROM_ESP', 8, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (19, '¿RECIBISTE BECA POR NECESIDAD ECONÓMICA EN LA SECUNDARIA?', 'BEC_NEC', 3, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (22, 'FALTO A CLASES', 'FRE_FCL', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (23, 'LLEVO TODOS LOS MATERIALES QUE UTILIZO EN LAS CLASES (LIBROS, CUADERNOS, LÁPICES, ETC.)', 'FRE_LLTM', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (24, 'PARTICIPO DURANTE LA CLASE', 'FRE_PDC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (25, 'DEDICO TIEMPO A ESTUDIAR FUERA DE LA ESCUELA', 'FRE_DTE', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (26, 'ENTREGO A TIEMPO LAS TAREAS QUE ME DEJAN EN LA ESCUELA', 'FRE_ETTE', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (27, 'PARTICIPO EN LA PLANEACIÓN DE LAS ACTIVIDADES', 'FRE_PPA', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (28, 'COLABORO EN EL DESARROLLO DE ESTRATEGIAS PARA CUMPLIR CON LAS METAS DEL TRABAJO', 'FRE_CDE', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (29, 'INTERVENGO PARA TRATAR DE SOLUCIONAR CONFLICTOS ENTRE LOS MIEMBROS DEL EQUIPO', 'FRE_TSC', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (30, 'REALIZO SUGERENCIAS PARA MEJORAR EL DESEMPEÑO DEL EQUIPO', 'FRE_SME', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (31, 'CUMPLO CON LAS TAREAS QUE ME TOCA REALIZAR', 'FRE_CTR', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (36, 'SI ME ESFUERZO LO SUFICIENTE, TENDRÉ ÉXITO EN LA ESCUELA', 'IDE_ESE', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (37, 'EL QUE ME VAYA BIEN O MAL EN LA ESCUELA DEPENDE TOTALMENTE DE MÍ', 'IDE_VBM', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (39, 'SI ME LO PROPONGO, ME VA MEJOR EN LA ESCUELA', 'IDE_PPM', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (44, 'SOY UNA PERSONA QUE SE ESMERA', 'DES_ESME', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (45, 'TERMINO TODO LO QUE EMPIEZO', 'DES_TERM', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (46, 'SOY UNA PERSONA QUE TRABAJA DURO', 'DES_DURO', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (47, 'PRESENTAR UN TRABAJO FRENTE A UN GRUPO', 'SOC_PTFG', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (48, 'INICIAR Y MANTENER UNA CONVERSACIÓN CON COMPAÑEROS QUE NO CONOCES', 'SOC_IMC', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (50, 'PLANTEAR DUDAS A LOS MAESTROS', 'SOC_PDM', 13, 125);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (61, 'IDENTIFICAR LAS DIFICULTADES PARA ALCANZAR TUS METAS', 'HAB_DAM', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (62, 'APRECIAR EL ARTE (COMO LA MÚSICA, LA DANZA Y LA PINTURA)', 'HAB_AEA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (63, 'TENER UN ESTILO DE VIDA SALUDABLE (HACER EJERCICIO, COMER SANAMENTE)', 'HAB_TEVS', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (64, 'LEER TEXTOS EN INGLÉS', 'HAB_LTI', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (65, 'EXPRESAR TUS IDEAS EN UN ESCRITO', 'HAB_ETI', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (66, 'EXPRESAR TUS IDEAS VERBALMENTE (DE MANERA ORAL)', 'HAB_ETIV', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (67, 'MANEJAR HOJAS DE CÁLCULO (COMO EXCEL)', 'HAB_MHC', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (68, 'ORDENAR INFORMACIÓN', 'HAB_OIF', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (69, 'IDENTIFICAR EL OBJETIVO DE LAS ACTIVIDADES QUE TE DEJAN EN LA ESCUELA', 'HAB_IOA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (70, 'EVALUAR TUS OPINIONES Y LAS DE OTRAS PERSONAS', 'HAB_ETO', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (71, 'APRENDER POR TI MISMO(A)', 'HAB_APM', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (72, 'REALIZAR EXPERIMENTOS EN LABORATORIOS O EN AMBIENTES NATURALES', 'HAB_REL', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (73, 'IDENTIFICAR Y SOLICITAR LA APLICACIÓN DE LAS LEYES QUE TE PROTEGEN COMO CIUDADANO(A)', 'HAB_SAL', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (74, 'DIALOGAR Y APRENDER DE OTRAS PERSONAS DISTINTOS PUNTOS DE VISTA Y TRADICIONES CULTURALES', 'HAB_DAP', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (75, 'CUIDAR EL MEDIO AMBIENTE', 'HAB_CMA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (76, '¿CUÁL ES EL NIVEL MÁXIMO DE ESTUDIOS QUE TE GUSTARÍA ALCANZAR?', 'EST_ALCA', 14, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (88, 'GOLPEARAN O MALTRATARAN FÍSICAMENTE?', 'DAN_MALF', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (89, 'OFENDIERAN CON INSULTOS, GROSERÍAS O APODOS HIRIENTES?', 'DAN_OFI', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (90, 'EXCLUYERAN, IGNORARAN O RECHAZARAN?', 'DAN_EIR', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (91, 'ROBARAN, ESCONDIERAN O QUITARAN TUS COSAS?', 'DAN_REQC', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (92, 'MOLESTARAN POR MEDIO DE REDES SOCIALES (FACEBOOK, TWITTER, ETC.), CORREO ELECTRÓNICO O MENSAJES DE TEXTO POR EL CELULAR?', 'DAN_MFT', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (93, 'FORZARAN A HACER COSAS QUE TÚ NO QUERÍAS?', 'DAN_FHC', 15, 131);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (94, '¿CUÁL ES EL MÁXIMO NIVEL DE ESTUDIOS DE TU MADRE (AUNQUE HAYA FALLECIDO)?', 'ESCO_MAD', 16, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (95, '¿CUÁL ES EL MÁXIMO NIVEL DE ESTUDIOS DE TU PADRE (AUNQUE HAYA FALLECIDO)?', 'ESCO_PAD', 16, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (96, '¿CUÁNTOS LIBROS HAY EN TU CASA? (NO CONSIDERES REVISTAS, PERIÓDICOS O TUS LIBROS DE TEXTO)', 'CUAN_LIB', 17, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (97, 'LÍNEA TELEFÓNICA FIJA', 'SER_TELE', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (98, 'LAVADORA DE ROPA', 'SER_LAV', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (99, 'REFRIGERADOR', 'SER_REF', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (100, 'HORNO DE MICROONDAS', 'SER_HOR', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (101, 'INTERNET', 'SER_INTE', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (102, 'TELEVISIÓN DE PAGA (IZZI, SKY, ETC.)', 'SER_CABL', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (103, 'TABLETA (IPAD, SAMSUNG GALAXY, PLAYBOOK, ETC.)', 'SER_TABL', 3, 132);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (104, 'COMPUTADORA', 'BIEN_PC', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (105, 'TELEVISOR', 'SER_TV', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (106, 'AUTOMÓVIL', 'SER_AUTO', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (107, 'BAÑOS COMPLETOS (CON REGADERA)', 'SER_BANO', 9, 133);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (108, '¿CUÁNTAS VECES HAS SALIDO DE VACACIONES DENTRO DE LA REPÚBLICA MEXICANA EN LOS ÚLTIMOS 2 AÑOS?', 'VAC_RM', 9, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (109, 'PADRES', 'INF_PAD', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (110, 'HERMANOS', 'INF_HER', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (111, 'AMIGOS', 'INF_AMI', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (112, 'PROFESORES', 'INF_PRF', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (113, 'PSICÓLOGOS U ORIENTADORES EDUCATIVOS', 'INF_POE', 18, 134);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (114, '¿UTILIZASTE LA GUÍA INTERACTIVA PARA PREPARARTE PARA EL EXANI-I (EXAMEN NACIONAL DE INGRESO A LA EDUCACIÓN MEDIA SUPERIOR)?', 'UTI_GUI', 3, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (115, 'EN TU ESCUELA', 'CUR_ESC', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (116, 'EN UNA INSTITUCIÓN PARTICULAR', 'CUR_IPA', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (117, 'CON UN MAESTRO PARTICULAR', 'CUR_MPA', 3, 135);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (118, '¿ENFRENTAS ALGUNAS DE LAS SIGUIENTES CONDICIONES?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (119, '¿ALGUNO DE TUS PADRES HABLA UNA LENGUA INDÍGENA O UN DIALECTO?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (120, '¿CON QUÉ FRECUENCIA REALIZAS LO SIGUIENTE?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (121, '¿CON QUÉ FRECUENCIA REALIZAS LO SIGUIENTE CUANDO TRABAJAS EN EQUIPO?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (123, 'INDICA QUÉ TANTO TE IDENTIFICAS CON LAS SIGUIENTES AFIRMACIONES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (124, 'INDICA QUÉ TANTO TE DESCRIBEN LAS SIGUIENTES AFIRMACIONES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (125, 'CALIFICA TU NIVEL DE HABILIDAD SOCIAL PARA REALIZAR LAS SIGUIENTES ACTIVIDADES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (128, 'CALIFICA TU NIVEL DE HABILIDAD PARA REALIZAR LAS SIGUIENTES ACTIVIDADES:', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (131, '¿QUÉ TANTO DAÑO TE CAUSÓ QUE TUS COMPAÑEROS EN LA SECUNDARIA TE…', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (132, '¿CUENTAS CON LOS SIGUIENTES BIENES Y SERVICIOS EN TU CASA?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (133, '¿CUÁNTOS DE LOS SIGUIENTES BIENES TIENES EN TU CASA?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (134, '¿QUÉ TANTO INFLUYERON LAS SIGUIENTES PERSONAS PARA ELEGIR LA ESCUELA PARA ESTUDIAR EL NIVEL MEDIO SUPERIOR?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (135, '¿TOMASTE UN CURSO DE PREPARACIÓN PARA EL EXANI-I (EXAMEN NACIONAL DE INGRESO A LA EDUCACIÓN MEDIA SUPERIOR)?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (142, 'LLEGO A TIEMPO A CLASES', 'FRE_LTC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (143, 'HAGO LOS EJERCICIOS QUE ME SOLICITAN EN LAS CLASES', 'FRE_HESC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (145, 'PONGO ATENCIÓN DURANTE LAS CLASES', 'FRE_PADC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (146, 'PARTICIPO EN ACTIVIDADES EXTRACURRICULARES QUE SE REALIZAN EN LA ESCUELA (ACTIVIDADES DEPORTIVAS, ARTÍSTICAS, ETC.)', 'FRE_PAEC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (147, 'SOY UNA PERSONA QUE SE ESFUERZA', 'DES_ESFU', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (148, 'PUEDO SUPERAR LOS OBSTÁCULOS QUE SE INTERPONEN PARA ALCANZAR MIS OBJETIVOS', 'DES_SOIO', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (149, 'HE ALCANZADO METAS QUE REQUIRIERON AÑOS DE ESFUERZO', 'DES_META', 12, 124);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (157, 'INDICA TU GRADO DE ACUERDO CON LOS SIGUIENTES ENUNCIADOS', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (173, '¿HASTA QUE NIVEL EDUCATIVO QUIEREN TUS PADRES QUE ESTUDIES?', 'NIV_EDU', 21, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (174, '¿CUÁNTAS PERSONAS VIVEN EN TU CASA?', 'CPV_CASA', 22, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (175, 'GENERALES', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (177, 'INDICA QUÉ TANTO ESTAS DE ACUERDO CON LOS SIGUIENTES ENUNCIADOS', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (188, '¿CON QUE FRECUENCIA REALIZAS LO SIGUIENTE CUANDO ESTUDIAS?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (199, 'CALIFICA TU NIVEL DE HABILIDAD PARA…', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (206, 'SIN CONTAR EL BAÑO, LA COCINA Y LOS PASILLOS, ¿CUÁNTOS CUARTOS TIENE TU CASA?', 'CUARTOS', 22, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (207, '¿QUÉ TANTO CONSIDERASTE LOS SIGUIENTES MEDIOS AL ELEGIR LA ESCUELA PARA ESTUDIAR EL NIVEL MEDIO SUPERIOR?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (208, 'FOLLETOS', 'CAR_FOLL', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (209, 'GUÍAS DE CARRERAS', 'CAR_GUIA', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (210, 'PÁGINAS DE INTERNET SOBRE ORIENTACIÓN VOCACIONAL', 'CAR_PIOV', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (211, 'PRUEBAS O TEST DE ORIENTACIÓN VOCACIONAL', 'CAR_PTOV', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (212, 'INTERCAMBIO INFORMACIÓN CON MIS COMPAÑEROS DE EQUIPO', 'FRE_IICE', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (213, 'ESCUCHO LAS IDEAS DE LOS OTROS INTEGRANTES DEL EQUIPO', 'FRE_EIIE', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (214, 'AYUDO A MIS COMPAÑEROS DE EQUIPO A CUMPLIR CON LAS TAREAS QUE LES TOCA REALIZAR', 'FRE_AECT', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (215, 'DIVIDO LAS TAREAS ENTRE LOS INTEGRANTES DEL EQUIPO PARA CONCLUIR EL TRABAJO MÁS RÁPIDO', 'FRE_DTCT', 10, 121);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (216, 'EXPLICO A OTRO COMPAÑERO ALGÚN TEMA APRENDIDO EN CLASE', 'SOC_EAA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (217, 'HABLO CON MIS COMPAÑEROS SOBRE TEMAS RELACIONADOS CON LOS TRABAJOS O TAREAS DE LA ESCUELA', 'SOC_HCT', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (218, 'CONVERSO CON LOS MAESTROS PARA PROFUNDIZAR SOBRE LOS TEMAS QUE SE REVISAN EN CLASE', 'SOC_CMP', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (219, 'PREGUNTO A OTRAS PERSONAS ACERCA DE TEMAS QUE NO ENTIENDO EN LAS CLASES', 'SOC_POA', 13, 128);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (220, 'ASISTO A TODAS LAS CLASES', 'FRE_ATC', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (221, 'PLANEO MIS ACTIVIDADES ESCOLARES', 'FRE_PLM', 10, 120);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (222, 'SI DEDICO SUFICIENTE TIEMPO A LA ESCUELA, OBTENGO MEJORES CALIFICACIONES', 'IDE_MCA', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (224, 'SI PONGO MÁS EMPEÑO AL ESTUDIAR, ME VA MEJOR EN LOS EXÁMENES', 'IDE_MEX', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (225, 'MIS CALIFICACIONES EN LA ESCUELA SON LA CONSECUENCIA DE LA ATENCIÓN QUE PONGO AL ESTUDIAR', 'IDE_ESTU', 11, 123);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (226, 'ME GUSTA LEER SOBRE LOS TEMAS QUE REVISO EN LA ESCUELA', 'IGA_LETE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (227, 'ME DIVIERTO CON LAS CLASES QUE RECIBO EN LA ESCUELA', 'IGA_DICE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (228, 'SOY FELIZ ESTUDIANDO LOS TEMAS QUE ME ENSEÑAN EN LA ESCUELA', 'IGA_FEES', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (229, 'DISFRUTO ADQUIRIENDO LA NUEVA INFORMACIÓN QUE RECIBO EN LAS CLASES', 'IGA_NUIN', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (230, 'ME INTERESA APRENDER COSAS NUEVAS SOBRE LOS TEMAS QUE REVISO EN LA ESCUELA', 'IGA_APCN', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (231, 'CUANDO ESTUDIO', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (232, 'PONGO MÁS ATENCIÓN CUANDO ENCUENTRO INFORMACIÓN IMPORTANTE', 'CES_PAE', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (233, 'APLICO EN LOS CURSOS ACTUALES LOS CONOCIMIENTOS QUE APRENDÍ EN CURSOS PASADOS', 'CES_ACA', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (234, 'SEPARO EN PARTES LA INFORMACIÓN DISPONIBLE', 'CES_SPI', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (235, 'HAGO DIBUJOS O DIAGRAMAS', 'CES_HDD', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (236, 'PONGO EN MIS PROPIAS PALABRAS LA INFORMACIÓN NUEVA', 'CES_PPP', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (237, 'RELACIONO LA INFORMACIÓN NUEVA CON LO QUE YA CONOZCO', 'CES_RIN', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (238, 'ANALIZO TODA LA INFORMACIÓN EN UN ÚNICO MOMENTO', 'CES_ATI', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (239, 'PONGO MAYOR ATENCIÓN EN LAS IDEAS GENERALES', 'CES_PMA', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (240, 'INVENTO MIS PROPIOS EJEMPLOS PARA ENTENDER MEJOR LA INFORMACIÓN', 'CES_IEI', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (241, 'IDENTIFICO LA ESTRUCTURA Y ORGANIZACIÓN DE LA INFORMACIÓN', 'CES_IEO', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (242, 'PONGO MAYOR ATENCIÓN EN LAS IDEAS ESPECÍFICAS', 'CES_MAI', 10, 231);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (243, 'LA PREPARACIÓN QUE RECIBO EN LA ESCUELA ES MUY ÚTIL PARA CONSEGUIR UN BUEN TRABAJO', 'IGA_PRE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (244, 'LAS CLASES QUE RECIBO EN LA ESCUELA SON NECESARIAS PARA ADQUIRIR NUEVOS CONOCIMIENTOS MÁS ADELANTE', 'IGA_CRE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (245, 'HACER LAS TAREAS QUE ME DEJAN EN LA ESCUELA ME AYUDA A PREPARARME MEJOR PARA EL FUTURO', 'IGA_HTE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (246, 'LO QUE APRENDO EN LAS CLASES ES ÚTIL PARA MI VIDA', 'IGA_ACV', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (247, 'LO QUE ME ENSEÑAN EN LA ESCUELA ES IMPORTANTE PARA LOGRAR MIS METAS PERSONALES', 'IGA_EEI', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (248, '¿CUÁL ES EL MÁXIMO NIVEL DE ESTUDIOS DEL JEFE O JEFA DE TU HOGAR?', 'ESCO_MAN', 16, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (249, '¿CUÁNTAS PERSONAS DE 14 AÑOS O MÁS QUE VIVEN EN TU HOGAR TRABAJARON EN EL ÚLTIMO MES?', 'CPA_MES', 9, 175);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (250, '¿QUÉ TANTO CONSIDERASTE LOS SIGUIENTES ASPECTOS AL ELEGIR LA ESCUELA PARA ESTUDIAR EL NIVEL MEDIO SUPERIOR (BACHILLERATO)?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (251, 'LA CALIDAD EDUCATIVA DE LA INSTITUCIÓN', 'QTC_CAE', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (252, 'LAS OPORTUNIDADES DE CONTINUAR LOS ESTUDIOS A NIVEL SUPERIOR QUE TIENEN LOS EGRESADOS DE LA INSTITUCIÓN', 'QTC_OPO', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (253, 'LAS OPORTUNIDADES DE EMPLEO QUE TIENEN LOS EGRESADOS DE LA INSTITUCIÓN', 'QTC_LOP', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (254, 'LA CALIDAD DE LOS MAESTROS DE LA INSTITUCIÓN', 'QTC_LCM', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (255, 'LAS INSTALACIONES DE LA ESCUELA (EDIFICIOS, SALONES, BIBLIOTECA, INSTALACIONES DEPORTIVAS, ETC.)', 'QTC_IES', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (256, 'EL TIEMPO DE TRASLADO DE TU CASA A LA ESCUELA', 'QTC_TIE', 18, 250);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (257, 'PLÁTICAS INFORMATIVAS EN TU ESCUELA', 'CAR_PLI', 18, 207);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (258, 'INDICA QUÉ TAN ADECUADOS SON LOS SIGUIENTES ESPACIOS O ASPECTOS DE TU ESCUELA', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (259, 'ASESORÍA ACADÉMICA', 'ASPC_ASA', 23, 258);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (260, 'TUTORÍAS', 'ASPC_TUT', 23, 258);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (261, 'INDICA LA CALIDAD DE LOS SIGUIENTES PROGRAMAS DE APOYO PARA LOS ALUMNOS DE TU ESCUELA', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (262, 'INTEGRACIÓN CULTURAL', 'APOY_ITC', 24, 261);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (263, 'DIFUSIÓN DE LA CULTURA', 'APOY_DIC', 24, 261);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (264, 'PROMOCIÓN DE LA CULTURA', 'APOY_PRC', 24, 261);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (265, 'FOMENTO A LA SALUD', 'APOY_SAL', 24, 261);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (266, 'PROGRAMA DE ATENCIÓN DE ADICCIONES', 'APOY_PAA', 24, 261);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (267, 'ME SIENTO FELIZ DE ESTAR EN ESTA ESCUELA', 'IGA_MFE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (268, 'ME SIENTO CERCANO(A) A MIS COMPAÑEROS DE LA ESCUELA', 'IGA_CCO', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (269, 'ME SIENTO SEGURO(A) EN MI ESCUELA', 'IGA_SEE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (270, 'ESTOY ORGULLOSO(A) DE ESTAR EN ESTA ESCUELA', 'IGA_ORG', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (271, 'SIENTO QUE SOY PARTE DE MI ESCUELA', 'IGA_PAE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (272, 'EN ESTA ESCUELA ME HACEN SENTIR ACEPTADO(A)', 'IGA_ACE', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (273, 'SIENTO QUE LA MAYORÍA DE MIS COMPAÑEROS Y MAESTROS COMPARTEN MIS OPINIONES Y CREENCIAS', 'IGA_OPI', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (274, 'EN LA ESCUELA SIEMPRE ENCUENTRO A PERSONAS QUE ME APOYAN', 'IGA_APO', 20, 177);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (275, '¿CON QUÉ FRECUENCIA TUS MAESTROS REALIZAN LAS SIGUIENTES ACTIVIDADES?', null, null, null);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (276, 'FALTAN A CLASE', 'FRE_FAC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (277, 'INICIAN Y TERMINAN LA CLASE PUNTUALMENTE', 'FRE_ITP', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (278, 'MANTIENEN LA DISCIPLINA EN EL SALÓN', 'FRE_MDS', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (279, 'USAN EL CELULAR DURANTE LA CLASE', 'FRE_UCC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (280, 'DEMUESTRAN UN CONOCIMIENTO ADECUADO DE LA MATERIA', 'FRE_DCM', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (281, 'PRESENTAN LOS TEMAS DE MANERA ORDENADA', 'FRE_PTO', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (282, 'HACEN LA CLASE INTERESANTE', 'FRE_HCI', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (283, 'UTILIZAN EJEMPLOS CERCANOS A LA REALIDAD (VIDA DIARIA) PARA AYUDAR A TU APRENDIZAJE', 'FRE_UEC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (284, 'RELACIONAN LOS CONOCIMIENTOS PREVIOS CON LOS NUEVOS', 'FRE_RCN', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (285, 'RESUELVEN DUDAS Y PREGUNTAS EN CLASE', 'FRE_RDPC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (286, 'HACEN EXÁMENES QUE CORRESPONDEN CON LO REVISADO EN CLASE', 'FRE_HEC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (287, 'DEJAN TRABAJOS Y TAREAS ADECUADOS PARA MI FORMACIÓN', 'FRE_DTT', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (288, 'DAN RETROALIMENTACIÓN DE LAS TAREAS', 'FRE_DRT', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (289, 'SOLICITAN UTILIZAR INFORMACIÓN DE INTERNET PARA REALIZAR LAS TAREAS', 'FRE_SUI', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (290, 'SOLICITAN UTILIZAR LA COMPUTADORA PARA REALIZAR LAS TAREAS', 'FRE_SUC', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (291, 'ESTIMULAN LA PARTICIPACIÓN DE LOS ALUMNOS', 'FRE_EPA', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (292, 'AYUDAN A LOS ALUMNOS QUE TIENEN DIFICULTADES CON ALGÚN TEMA', 'FRE_AYA', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (293, 'TOMAN EN CUENTA A TODOS LOS ALUMNOS', 'FRE_TEA', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (294, 'TRATAN CON RESPETO A LOS ALUMNOS', 'FRE_TRA', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (295, 'FOMENTAN EL RESPETO ENTRE LOS ALUMNOS', 'FRE_FRA', 10, 275);
INSERT INTO educacionmedia.ceneval_preguntas (id, nombre, variable, diccionario_id, padre_id) VALUES (296, 'ORGANIZAN TRABAJO EN EQUIPO', 'FRE_OTE', 10, 275);
SET FOREIGN_KEY_CHECKS = 1;
