SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.ceneval_diccionarios;
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (22, '1_A_6_O_MAS');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (20, 'ACUERDO_DESACUERDO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (1, 'ENTIDAD_FEDERATIVA');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (16, 'ESTUDIOS_PADRES');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (17, 'LIBROS_EN_MI_CASA');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (12, 'ME_DESCRIBE');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (14, 'ME_GUSTARIA_ESTUDIAR_HASTA');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (11, 'ME_IDENTIFICO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (15, 'ME_SUCEDIO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (19, 'NADA_HABIL_MUY_HABIL');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (9, 'NINGUNO_4_MAS');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (21, 'NIV_EDU_DIC');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (13, 'NO_LO_SE_HACER');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (10, 'NUNCA_SIEMPRE');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (18, 'POCO_NADA_MUCHO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (8, 'PROMEDIOS');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (5, 'PUBLICO_PRIVADO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (2, 'SEXO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (3, 'SI_NO');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (4, 'SI_NO_NOSE');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (6, 'TIPO_ESCUELA');
INSERT INTO educacionmedia.ceneval_diccionarios (id, nombre) VALUES (7, 'TURNO');
SET FOREIGN_KEY_CHECKS = 1;
