SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.ceneval_respuestas;
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (1, '01', 'Aguascalientes', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (2, '02', 'Baja California', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (3, '03', 'Baja California Sur', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (4, '04', 'Campeche', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (5, '05', 'Coahuila', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (6, '06', 'Colima', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (7, '07', 'Chiapas', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (8, '08', 'Chihuahua', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (9, '09', 'Distrito Federal', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (10, '10', 'Durango', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (11, '11', 'Guanajuato', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (12, '12', 'Guerrero', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (13, '13', 'Hidalgo', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (14, '14', 'Jalisco', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (15, '15', 'Estado de México', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (16, '16', 'Michoacán', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (17, '17', 'Morelos', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (18, '18', 'Nayarit', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (19, '19', 'Nuevo León', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (20, '20', 'Oaxaca', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (21, '21', 'Puebla', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (22, '22', 'Querétaro', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (23, '23', 'Quintana Roo', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (24, '24', 'San Luis Potosí', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (25, '25', 'Sinaloa', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (26, '26', 'Sonora', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (27, '27', 'Tabasco', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (28, '28', 'Tamaulipas', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (29, '29', 'Tlaxcala', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (30, '30', 'Veracruz', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (31, '31', 'Yucatán', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (32, '32', 'Zacatecas', 1);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (33, '1', 'Hombre', 2);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (34, '2', 'Mujer', 2);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (35, '1', 'Si', 3);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (36, '2', 'No', 3);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (37, '1', 'Si', 4);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (38, '2', 'No', 4);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (39, '3', 'No sé', 4);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (40, '1', 'Público', 5);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (41, '2', 'Privado', 5);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (42, '1', 'Secundaria general', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (43, '2', 'Secundaria técnica', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (44, '3', 'Secundaria comunitaria', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (45, '4', 'Telesecundaria', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (46, '5', 'Secundaria abierta', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (47, '6', 'Otro', 6);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (48, '1', 'Matutino', 7);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (49, '2', 'Vespertino', 7);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (50, '3', 'Nocturno', 7);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (51, '4', 'No aplica (Acuerdo 286, para adultos o INEA, secundaria abierta)', 7);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (53, '6.0', '6.0', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (54, '6.1', '6.1', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (55, '6.2', '6.2', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (56, '6.3', '6.3', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (57, '6.4', '6.4', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (58, '6.5', '6.5', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (59, '6.6', '6.6', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (60, '6.7', '6.7', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (61, '6.8', '6.8', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (62, '1', 'Ninguno', 9);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (63, '2', '1', 9);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (64, '3', '2', 9);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (65, '4', '3', 9);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (66, '5', '4 o más', 9);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (67, '1', 'Nunca o casi nunca', 10);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (68, '2', 'Algunas veces', 10);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (69, '3', 'Frecuentemente', 10);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (70, '4', 'Siempre o casi siempre', 10);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (71, '1', 'No me identifico', 11);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (72, '2', 'Me identifico poco', 11);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (73, '3', 'Me identifico', 11);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (74, '4', 'Me identifico totalmente', 11);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (75, '1', 'No me describe', 12);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (76, '2', 'Me describe poco', 12);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (77, '3', 'Me describe', 12);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (78, '4', 'Me describe mucho', 12);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (79, '1', 'No lo sé hacer', 13);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (80, '2', 'Poco hábil', 13);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (81, '3', 'Hábil', 13);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (82, '4', 'Muy hábil', 13);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (83, '1', 'Bachillerato', 14);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (84, '2', 'Carrera técnica', 14);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (85, '3', 'Técnico superior universitario (después del bachillerato)', 14);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (86, '4', 'Licenciatura', 14);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (87, '5', 'Posgrado (especialidad, maestría, doctorado)', 14);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (88, '1', 'No me sucedió', 15);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (89, '2', 'Nada de daño', 15);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (90, '3', 'Poco daño', 15);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (91, '4', 'Algo de daño', 15);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (92, '5', 'Mucho daño', 15);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (93, '01', 'No estudió', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (94, '02', 'Primaria incompleta', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (95, '03', 'Primaria completa', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (96, '04', 'Secundaria incompleta', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (97, '05', 'Secundaria completa', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (98, '06', 'Bachillerato (nivel medio superior) incompleto', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (99, '07', 'Bachillerato (nivel medio superior) completo', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (100, '08', 'Carrera técnica incompleta', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (101, '1', 'Ninguno', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (102, '2', '1 a 10', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (103, '3', '11 a 25 (ocupan la mitad de un estante)', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (104, '4', '26 a 50 (un estante)', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (105, '5', '51 a 100 (dos o tres estantes)', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (106, '6', '101 a 200 (cinco estantes)', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (107, '7', '201 a 500 (diez estantes o dos libreros)', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (108, '8', 'Más de 500', 17);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (109, '1', 'Nada', 18);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (110, '2', 'Poco', 18);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (111, '3', 'Algo', 18);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (112, '4', 'Mucho', 18);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (113, '1', 'NADA HÁBIL', 19);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (114, '2', 'POCO HÁBIL', 19);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (115, '3', 'HÁBIL', 19);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (116, '4', 'MUY HÁBIL', 19);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (117, '1', 'Totalmente en desacuerdo', 20);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (118, '2', 'En desacuerdo', 20);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (119, '3', 'De acuerdo', 20);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (120, '4', 'Totalmente de acuerdo', 20);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (121, '1', 'Secundaria', 21);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (122, '2', 'Nivel medio superior', 21);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (123, '3', 'Carrera técnica superior (después del bachillerato)', 21);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (124, '4', 'Licenciatura', 21);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (125, '5', 'Posgrado (especialidad, maestría, doctorado)', 21);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (126, '1', '1', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (127, '2', '2', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (128, '3', '3', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (129, '4', '4', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (130, '5', '5', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (131, '6', '6 o más', 22);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (132, '6.9', '6.9', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (133, '7.0', '7.0', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (134, '7.1', '7.1', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (135, '7.2', '7.2', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (136, '7.3', '7.3', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (137, '7.4', '7.4', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (138, '7.5', '7.5', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (139, '7.6', '7.6', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (140, '7.7', '7.7', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (141, '7.8', '7.8', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (142, '7.9', '7.9', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (143, '8.0', '8.0', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (144, '8.1', '8.1', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (145, '8.2', '8.2', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (146, '8.3', '8.3', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (147, '8.4', '8.4', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (148, '8.5', '8.5', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (149, '8.6', '8.6', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (150, '8.7', '8.7', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (151, '8.8', '8.8', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (152, '8.9', '8.9', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (153, '9.0', '9.0', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (154, '9.1', '9.1', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (155, '9.2', '9.2', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (156, '9.3', '9.3', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (157, '9.4', '9.4', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (158, '9.5', '9.5', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (159, '9.6', '9.6', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (160, '9.7', '9.7', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (161, '9.8', '9.8', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (162, '9.9', '9.9', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (163, '10.0', '10.0', 8);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (164, '09', 'Carrera técnica completa', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (165, '10', 'Técnico superior universitario (después del bachillerato) incompleto', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (166, '11', 'Técnico superior universitario (después del bachillerato) completo', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (167, '12', 'Licenciatura incompleta', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (168, '13', 'Licenciatura completa', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (169, '14', 'Posgrado (especialidad, maestría, doctorado)', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (170, '15', 'No lo sé', 16);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (171, '1', 'No hay', 23);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (172, '2', 'Nada adecuados', 23);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (173, '3', 'Poco adecuados', 23);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (174, '4', 'Adecuados', 23);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (175, '5', 'Muy adecuados', 23);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (176, '1', 'No hay', 24);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (177, '2', 'Mala', 24);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (178, '3', 'Regular', 24);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (179, '4', 'Buena', 24);
INSERT INTO educacionmedia.ceneval_respuestas (id, valor, etiqueta, diccionario_id) VALUES (180, '5', 'Excelente', 24);
SET FOREIGN_KEY_CHECKS = 1;
