set FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.entidades;
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('01', 'AGUASCALIENTES');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('02', 'BAJA CALIFORNIA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('03', 'BAJA CALIFORNIA SUR');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('04', 'CAMPECHE');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('05', 'COAHUILA DE ZARAGOZA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('06', 'COLIMA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('07', 'CHIAPAS');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('08', 'CHIHUAHUA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('09', 'CIUDAD DE MÉXICO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('10', 'DURANGO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('11', 'GUANAJUATO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('12', 'GUERRERO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('13', 'HIDALGO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('14', 'JALISCO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('15', 'MÉXICO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('16', 'MICHOACÁN DE OCAMPO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('17', 'MORELOS');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('18', 'NAYARIT');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('19', 'NUEVO LEÓN');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('20', 'OAXACA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('21', 'PUEBLA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('22', 'QUERÉTARO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('23', 'QUINTANA ROO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('24', 'SAN LUIS POTOSÍ');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('25', 'SINALOA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('26', 'SONORA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('27', 'TABASCO');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('28', 'TAMAULIPAS');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('29', 'TLAXCALA');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('30', 'VERACRUZ DE IGNACIO DE LA LLAVE');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('31', 'YUCATÁN');
INSERT INTO educacionmedia.entidades (id, descripcion) VALUES ('32', 'ZACATECAS');
set FOREIGN_KEY_CHECKS = 1;
