SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE educacionmedia.programas_estudio;
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (1, 'AGRONOMIA', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (2, 'ARTES', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (3, 'EDUCACION', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (4, 'INGENIERIA', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (5, 'NATURALES', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (6, 'SALUD', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (7, 'SERVICIOS', null, null);
INSERT INTO educacionmedia.programas_estudio (id, descripcion, created_at, updated_at) VALUES (8, 'SOCIALES', null, null);
SET FOREIGN_KEY_CHECKS = 1;
