<?php
/**
 * Created by PhpStorm.
 * User: igna
 */

namespace MediaSuperior\Providers;


use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'MediaSuperior\Http\Controllers';

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map()
    {
        $this->mapWebRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::prefix('media')
            ->middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('app/Modules/MediaSuperior/Routes/web.php'));
    }
}
