<?php

namespace Plantel\Providers;


use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;

class RouteServiceProvider extends ServiceProvider
{
    protected $namespace = 'Plantel\Http\Controllers';

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map()
    {
        $this->mapApiRoutes();

        $this->mapWebRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::prefix('planteles')
            ->middleware('web')
            ->namespace($this->namespace)
            ->group(base_path('app/Modules/Plantel/Routes/web.php'));
    }

    protected function mapApiRoutes()
    {
        Route::prefix('api/planteles')
            ->middleware('api')
            ->namespace($this->namespace)
            ->group(base_path('app/Modules/Plantel/Routes/api.php'));
    }
}
